### PR TITLE
[Sysnotify] Handle non-initialised plugin.

### PR DESCRIPTION
**Pull request by MPogoda**
This fixes segfault during startup of application.

### CODE REVIEW

**Comment by 0xd34df00d** [comment]
BTW what plugins are causing this?

Emitting an entity from a plugin before its SecondInit() is called could be considered a bug.

**Comment by MPogoda** [comment]
It is bittorrent.
It was trying to notify about (changed?) ports or something like that.
Every startup.

I'll reproduce this in a moment to gather better logs.

**Comment by MPogoda** [comment]
[15.05.2015 00:57:05.155] [0x1a27750] [034] void LeechCraft::BitTorrent::SessionSettingsManager::tcpPortRangeChanged() error listening on 6881 6889 Address family not supported by protocol

**Comment by MPogoda** [comment]
BTW, it is not building now >_>

**Pull request merged**
